name: ci

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  go-fmt:
    name: go-fmt
    runs-on: ubuntu-20.04

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Checkout branch
        uses: actions/checkout@v3

      # Fail if go-fmt recommends any changes.
      - name: Run go fmt
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
